### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by kazu-yamamoto** [Certerazvi/h2specd#7]
When Firefox accesses to http://127.0.0.1:2443/, the following error happens. I cannot succeed in the automatic testing at this moment.

```
The address for testing is: 
https://localhost:2443
2016/08/04 16:21:54 http2: panic serving 127.0.0.1:53502: runtime error: invalid memory address or nil pointer dereference
goroutine 24 [running]:
h2specd.(*http2serverConn).runHandler.func1(0xc820187f6f, 0xc820370000, 0xc82014e018)
    /Users/Razvan/HTTP2/src/h2specd/h2_bundle.go:4344 +0xbc
panic(0x3af080, 0xc82000a130)
    /usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:443 +0x4e9
html/template.(*Template).escape(0x0, 0x0, 0x0)
    /usr/local/Cellar/go/1.6.2/libexec/src/html/template/template.go:79 +0x3c
html/template.(*Template).Execute(0x0, 0x16001b0, 0xc82014e018, 0x4053c0, 0xc820192de0, 0x0, 0x0)
    /usr/local/Cellar/go/1.6.2/libexec/src/html/template/template.go:101 +0x34
main.hello(0x1600150, 0xc82014e018, 0xc8203230a0)
    /Users/Razvan/HTTP2/src/h2specd/cmd/h2specd.go:84 +0x123
h2specd.HandlerFunc.ServeHTTP(0x4e0268, 0x1600150, 0xc82014e018, 0xc8203230a0)
    /Users/Razvan/HTTP2/src/h2specd/server.go:1622 +0x3a
h2specd.(*ServeMux).ServeHTTP(0xc820015140, 0x1600150, 0xc82014e018, 0xc8203230a0)
    /Users/Razvan/HTTP2/src/h2specd/server.go:1917 +0x17d
h2specd.serverHandler.ServeHTTP(0xc820082080, 0x1600150, 0xc82014e018, 0xc8203230a0)
    /Users/Razvan/HTTP2/src/h2specd/server.go:2085 +0x19e
h2specd.initNPNRequest.ServeHTTP(0xc820228300, 0xc820082080, 0x1600150, 0xc82014e018, 0xc8203230a0)
    /Users/Razvan/HTTP2/src/h2specd/server.go:2513 +0x221
h2specd.(*initNPNRequest).ServeHTTP(0xc820147070, 0x1600150, 0xc82014e018, 0xc8203230a0)
    <autogenerated>:265 +0xb6
h2specd.(Handler).ServeHTTP-fm(0x1600150, 0xc82014e018, 0xc8203230a0)
    /Users/Razvan/HTTP2/src/h2specd/h2_bundle.go:4141 +0x50
h2specd.(*http2serverConn).runHandler(0xc820370000, 0xc82014e018, 0xc8203230a0, 0xc82037c040)
    /Users/Razvan/HTTP2/src/h2specd/h2_bundle.go:4354 +0x9f
created by h2specd.(*http2serverConn).processHeaderBlockFragment
    /Users/Razvan/HTTP2/src/h2specd/h2_bundle.go:4147 +0x55e
```

**Comment by Certerazvi** [comment]
This was caused because it did not find the needed html file. I added it now to the zip file in the new release (v0.0.6.1). I will close the issue now.
